### ISSUE TITLE
Add Custom Message option to can_definition

### ISSUE THREAD

**Issue by Exoth** [CanCanCommunity/cancancan#202]
I would like to continue this unresolved CanCan issue here.
https://github.com/ryanb/cancan/issues/103

As was mentioned by @mcfiredrill, there's no way to have different authorization error messages for the same action+subject combination but for different rules. It's quite important to be able to tell the user not only that he is not able to do something, but also why he isn't able to do it. So it would be really great if there's a way to specify a separate error message for every rule (fallbacking to existing message mechanism, if not specified).

**Comment by sengenbe** [comment]
+1

**Comment by Yanchek99** [comment]
+1

**Comment by Senjai** [comment]
@Exoth :+1: I can't say this would be a super high priority at the moment, but it would be something I could see coming into the project for sure.

**Comment by marchbnr** [comment]
+1

**Comment by coorasse** [comment]
Am I wrong or this is already implemented? https://github.com/ryanb/cancan/commit/a5f838a964f8717c3243eb6e2d5cd3a949a8986a#diff-d4e0a70d43eb4c389e623945f417d6e0R203

You have simply to define them into yml file

```
en:
  unauthorized:
    default: "You don't have the required permissions to execute this action"
    create:
      group: "You cannot create the group because you didn't pay enough"
```
